############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "GitHub"
url = "https://github.com/leenooks/phpldapadmin"
weight = 2

[[main]]
name = "Docker"
url = "https://hub.docker.com/r/phpldapadmin/phpldapadmin"
weight = 3

[[main]]
name = "Wiki"
url = "https://github.com/leenooks/phpldapadmin/wiki"
weight = 4

[[main]]
name = "Help"
url = "https://github.com/leenooks/phpldapadmin/discussions"
weight = 6

[[main]]
name = "Demo"
weight = 5

[[main]]
parent = "Demo"
name = "Openldap"
url = "https://demo-openldap.phpldapadmin.org"
weight = 1

[[main]]
parent = "Demo"
name = "389 DS"
url = "https://demo-389ds.phpldapadmin.org"
weight = 2

[[main]]
parent = "Demo"
name = "Apache DS"
url = "https://demo-apacheds.phpldapadmin.org"
weight = 2

[[main]]
parent = "Demo"
name = "OpenDJ"
url = "https://demo-opendj.phpldapadmin.org"
weight = 2

[[main]]
parent = "Demo"
name = "LLDAP"
url = "https://demo.phpldapadmin.org/lldap"
weight = 2

[[main]]
parent = "Demo"
name = "OpenBSD ldapd"
url = "https://demo-ldapd.phpldapadmin.org"
weight = 2

[[main]]
parent = "Demo"
name = "Development"
url = "https://demo-dev.phpldapadmin.org"
weight = 3

# footer menu
#[[footer]]
#name = "Github"
#url = "/about"
#weight = 1

#[[footer]]
#name = "Wiki"
#url = "/elements"
#weight = 2
